version: "2.2"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: dell_new1
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/demo_shopify_app
    ports:
      - "3000:3000"
    depends_on:
      - db
  redis:
    image: redis:5.0.7
    ports:
      - 6379:6379
  sidekiq:
    build: .
    volumes:
      - ".:/demo_shopify_app"
    links:
      - db
      - redis