default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: dell_new1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: demo_shopify_app_development

test:
  <<: *default
  database: demo_shopify_app_test

production:
  <<: *default
  database: demo_shopify_app_production
  username: demo_shopify_app
  password: <%= ENV['DEMO_SHOPIFY_APP_DATABASE_PASSWORD'] %>
